In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [21]:
pd.set_option('display.max_columns',None)

In [22]:
df = pd.read_csv(r'C:\Users\HARSHIT JAIN\Desktop\data science projects\Credit Risk Modeling\DATASET\merge_dataset.csv')

In [23]:
df

,PROSPECTID,Total trade lines accounts,Total closed trade lines accounts,Total active accounts,Total accounts opened in last 6 Months,Total accounds closes in last 6 months,Percent accounts opened in last 6 months,percent accounts closed in last 6 months,Percent active accounts,Percent closed accounts,Total accounts opened in last 12 Months,Total accounts closed in last 12 months,Percent accounts opened in last 12 months,percent accounts closed in last 12 months,Total missed Payments,Count Automobile accounts,Count of Credit card accounts,Count of Consumer goods accounts,Count of Gold loan accounts,Count of Housing loan accounts,Count of Personal loan accounts,Count of secured accounts,Count of unsecured accounts,Count of other accounts,Age of oldest opened account,Age of newest opened account,Time Since recent Payment made,Number of times delinquent,Maximum recent level of delinquency,Number of times delinquent in last 6 months,Number of times delinquent in last 12 months,Number of times delinquent between last 6 months and last 12 months,Number of times 30+ dpd,Number of times 60+ dpd,Number of standard Payments,Number of standard Payments in last 6 months,Number of standard Payments in last 12 months,Number of sub standard payments - not making full payments,Number of sub standard payments in last 6 months,Number of sub standard payments in last 12 months,Number of doubtful payments,Number of doubtful payments in last 6 months,Number of doubtful payments in last 12 months,Number of loss accounts,Number of loss accounts in last 6 months,Number of loss accounts in last 12 months,Recent level of delinquency,Total enquiries,Credit card enquiries,Credit card enquiries in last 6 months,Credit card enquiries in last 12 months,Personal Loan enquiries,Personal Loan enquiries in last 6 months,Personal Loan enquiries in last 12 months,Time since recent enquiry,Enquiries in last 12 months,Enquiries in last 6 months,Enquiries in last 3 months,Marital Status,Education level,Age,gender,net monthly income,Time with current Employer,Percent active accounts ever,Percent accounts opened in last 6 months to last 12 months,Percent current balance of all accounts,Credit card Flag,Personal Loan Flag,Percent enquiries PL in last 6 months to last 12 months,Percent enquiries CC in last 6 months to last 12 months,Percent enquiries PL in last 6 months to last 6 months,Percent enquiries CC in last 6 months to last 6 months,Housing Loan Flag,Gold Loan Flag,Lates product enquired,First productd enquired,Applicant's credit score,Priority levels
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,0,0,0.000,0.000,0,0,0,0,1,0,4,1,4,0,72,18,549,11,29,0,0,0,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,0,1,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,1,0,1.000,0.000,0,0,0,1,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,0,0,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,2,0,0.250,0.000,1,1,0,6,1,0,0,2,6,0,47,2,302,9,25,1,9,8,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,0,0,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,0,0,0.000,0.000,0,1,0,0,0,0,0,3,0,2,131,32,583,0,0,0,0,0,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,0,0,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,0,1,0.000,0.167,0,4,0,0,2,0,0,6,0,0,150,17,245,14,270,0,0,0,13,11,5,0,2,3,0,1,0,0,0,0,0,0,26,15,2,0,1,7,3,3,7,6,5,4,Married,12TH,35,M,0,154,0.167,0.0,0.000,0,0,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,1,0,0.333,0.000,0,0,0,2,0,0,0,0,3,1,24,5,15,2,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,4,0,0,0,0,0,0,0,3,3,1,Married,12TH,43,M,18500,249,1.000,1.0,0.230,0,0,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,2,1,0.500,0.250,0,2,0,2,0,0,0,2,2,0,74,7,57,0,0,0,0,0,0,0,6,4,6,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,203,1,0,0,Married,SSC,31,M,25000,186,0.500,0.0,0.660,0,0,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,2,1,1.000,0.500,0,0,0,2,0,0,0,0,2,0,9,5,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,2,2,2,1,5,4,2,Married,SSC,28,M,18000,66,0.500,0.5,0.428,0,0,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,1,1,0.500,0.500,0,0,0,2,0,0,0,0,2,0,15,8,58,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,242,1,0,0,Single,UNDER GRADUATE,25,F,12802,54,0.500,0.0,0.143,0,0,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,0,0,0.000,0.000,0,1,0,0,0,0,0,1,0,0,20,20,74,0,0,0,0,0,0,0,18,4,10,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,13,1,1,1,Married,SSC,25,M,16000,102,1.000,0.0,0.333,0,0,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

In [28]:
df.rename(columns={'Priority levels':'Approved_Flag'},inplace=True)

In [29]:
for i in df.columns:
    if df[i].dtype == 'object':
         print(i)

Marital Status
Education level
gender
Lates product enquired
First productd enquired
Approved_Flag

In [30]:
for i in ['Marital Status', 'Education level', 'gender', 'Lates product enquired', 'First productd enquired']:
    chi2, pval, _, _ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

Marital Status --- 3.578180861038862e-233
Education level --- 2.6942265249737532e-30
gender --- 1.907936100186563e-05
Lates product enquired --- 0.0
First productd enquired --- 7.84997610555419e-287

In [31]:
numeric_columns = []
for i in df.columns:
    if df[i].dtype != 'object' and i not in ['PROSPECTID','Approved_Flag']:
        numeric_columns.append(i)

In [32]:
vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0

In [33]:
for i in range (0,total_columns):
    
    vif_value = variance_inflation_factor(vif_data, column_index)
    print (column_index,'---',vif_value)
    
    
    if vif_value <= 6:
        columns_to_be_kept.append( numeric_columns[i] )
        column_index = column_index+1
    
    else:
        vif_data = vif_data.drop([ numeric_columns[i] ] , axis=1)

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000336
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.8328007921530785
3 --- 6.099653381646727
3 --- 5.581352009642766
4 --- 1.985584353098778

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.809538302819343
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.384346405965583
7 --- 3.064658415523423
8 --- 2.898639771299251
9 --- 4.377876915347324
10 --- 2.2078535836958433
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721438

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427232
15 --- 1.421005001517573
16 --- 8.083255010190323
16 --- 1.624122752404011
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.825857047132431
18 --- 1.5080839450032664
19 --- 2.172088834824577
20 --- 2.623397553527229
21 --- 2.2959970812106167
22 --- 7.360578319196446
22 --- 2.1602387773102554
23 --- 2.8686288267891467
24 --- 6.458218003637277
24 --- 2.8474118865638247
25 --- 4.753198156284083
26 --- 16.227354755948223
26 --- 6.424377256363877
26 --- 8.887080381808687
26 --- 2.3804746142952653
27 --- 8.609513476514548
27 --- 13.06755093547673
27 --- 3.5000400566546555
28 --- 1.9087955874813773
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.104855915136433
30 --- 2.7971639638512915
31 --- 3.424171203217697
32 --- 10.175021454450922
32 --- 6.408710354561292
32 --- 1.0011511962625619
33 --- 3.069197305397274
34 --- 2.8091261600643724
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.833164974053215
36 --- 1.5680839909542044
37 --- 1.9307572353811682
38 --- 4.331265056645249
39 --- 9.390334396150173

In [34]:
from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])  
    b = list(df['Approved_Flag'])  
    
    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)

In [38]:
features = columns_to_be_kept_numerical + ['Marital Status', 'Education level', 'gender', 'Lates product enquired', 'First productd enquired']
df_new = df[features + ['Approved_Flag']]

In [39]:
df_new

,Percent accounts opened in last 6 months,percent accounts closed in last 6 months,Total accounts closed in last 12 months,percent accounts closed in last 12 months,Total missed Payments,Count of Credit card accounts,Count of Housing loan accounts,Count of Personal loan accounts,Count of secured accounts,Count of unsecured accounts,Count of other accounts,Age of oldest opened account,Age of newest opened account,Time Since recent Payment made,Maximum recent level of delinquency,Number of times delinquent between last 6 months and last 12 months,Number of times 60+ dpd,Number of standard Payments in last 12 months,Number of sub standard payments - not making full payments,Number of sub standard payments in last 6 months,Number of sub standard payments in last 12 months,Number of doubtful payments,Number of doubtful payments in last 12 months,Number of loss accounts,Recent level of delinquency,Credit card enquiries in last 12 months,Personal Loan enquiries in last 12 months,Time since recent enquiry,Enquiries in last 3 months,net monthly income,Time with current Employer,Credit card Flag,Personal Loan Flag,Percent enquiries PL in last 6 months to last 6 months,Percent enquiries CC in last 6 months to last 6 months,Housing Loan Flag,Gold Loan Flag,Marital Status,Education level,gender,Lates product enquired,First productd enquired,Approved_Flag
0,0.000,0.00,0,0.000,0,0,0,4,1,4,0,72,18,549,29,0,0,11,0,0,0,0,0,0,29,0,0,566,0,51000,114,0,1,0.000,0.0,1,0,Married,12TH,M,PL,PL,P2
1,0.000,0.00,0,0.000,0,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,209,0,19000,50,0,0,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.00,0,0.000,1,0,0,0,2,6,0,47,2,302,25,8,0,10,0,0,0,0,0,0,25,0,0,587,0,18,191,0,0,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,0.000,0.00,0,0.000,0,0,0,0,3,0,2,131,32,583,0,0,0,16,0,0,0,0,0,0,0,0,0,3951,0,15000,75,0,0,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1
4,0.000,0.00,1,0.167,0,0,0,0,6,0,0,150,17,245,270,0,11,2,3,0,1,0,0,0,26,1,3,7,4,0,154,0,0,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,0.333,0.00,0,0.000,0,0,0,0,0,3,1,24,5,15,24,0,0,0,0,0,0,0,0,0,24,0,0,0,1,18500,249,0,0,0.000,0.0,0,0,Married,12TH,M,ConsumerLoan,ConsumerLoan,P4
42060,0.000,0.25,1,0.250,0,0,0,0,2,2,0,74,7,57,0,0,0,6,0,0,0,0,0,0,0,0,0,203,0,25000,186,0,0,0.000,0.0,0,0,Married,SSC,M,others,others,P1
42061,0.500,0.50,1,0.500,0,0,0,0,0,2,0,9,5,32,0,0,0,0,0,0,0,0,0,0,0,0,2,1,2,18000,66,0,0,1.000,0.0,0,0,Married,SSC,M,ConsumerLoan,others,P3
42062,0.000,0.00,1,0.500,0,0,0,0,0,2,0,15,8,58,0,0,0,0,0,0,0,0,0,0,0,0,0,242,0,12802,54,0,0,0.000,0.0,0,0,Single,UNDER GRADUATE,F,ConsumerLoan,others,P2
42063,0.000,0.00,0,0.000,0,0,0,0,1,0,0,20,20,74,0,0,0,10,0,0,0,0,0,0,0,0,0,13,1,16000,102,0,0,0.000,0.0,0,0,Married,SSC,M,others,others,P2

In [40]:
df_new.to_csv('feature_selection.csv',index=False)