In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import  StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_val_score

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv(r'C:\Users\HARSHIT JAIN\Desktop\data science projects\Credit Risk Modeling\DATASET\feature_selection.csv')

In [4]:
df

,Percent accounts opened in last 6 months,percent accounts closed in last 6 months,Total accounts closed in last 12 months,percent accounts closed in last 12 months,Total missed Payments,Count of Credit card accounts,Count of Housing loan accounts,Count of Personal loan accounts,Count of secured accounts,Count of unsecured accounts,Count of other accounts,Age of oldest opened account,Age of newest opened account,Time Since recent Payment made,Maximum recent level of delinquency,Number of times delinquent between last 6 months and last 12 months,Number of times 60+ dpd,Number of standard Payments in last 12 months,Number of sub standard payments - not making full payments,Number of sub standard payments in last 6 months,Number of sub standard payments in last 12 months,Number of doubtful payments,Number of doubtful payments in last 12 months,Number of loss accounts,Recent level of delinquency,Credit card enquiries in last 12 months,Personal Loan enquiries in last 12 months,Time since recent enquiry,Enquiries in last 3 months,net monthly income,Time with current Employer,Credit card Flag,Personal Loan Flag,Percent enquiries PL in last 6 months to last 6 months,Percent enquiries CC in last 6 months to last 6 months,Housing Loan Flag,Gold Loan Flag,Marital Status,Education level,gender,Lates product enquired,First productd enquired,Approved_Flag
0,0.000,0.00,0,0.000,0,0,0,4,1,4,0,72,18,549,29,0,0,11,0,0,0,0,0,0,29,0,0,566,0,51000,114,0,1,0.000,0.0,1,0,Married,12TH,M,PL,PL,P2
1,0.000,0.00,0,0.000,0,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,209,0,19000,50,0,0,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.00,0,0.000,1,0,0,0,2,6,0,47,2,302,25,8,0,10,0,0,0,0,0,0,25,0,0,587,0,18,191,0,0,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,0.000,0.00,0,0.000,0,0,0,0,3,0,2,131,32,583,0,0,0,16,0,0,0,0,0,0,0,0,0,3951,0,15000,75,0,0,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1
4,0.000,0.00,1,0.167,0,0,0,0,6,0,0,150,17,245,270,0,11,2,3,0,1,0,0,0,26,1,3,7,4,0,154,0,0,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,0.333,0.00,0,0.000,0,0,0,0,0,3,1,24,5,15,24,0,0,0,0,0,0,0,0,0,24,0,0,0,1,18500,249,0,0,0.000,0.0,0,0,Married,12TH,M,ConsumerLoan,ConsumerLoan,P4
42060,0.000,0.25,1,0.250,0,0,0,0,2,2,0,74,7,57,0,0,0,6,0,0,0,0,0,0,0,0,0,203,0,25000,186,0,0,0.000,0.0,0,0,Married,SSC,M,others,others,P1
42061,0.500,0.50,1,0.500,0,0,0,0,0,2,0,9,5,32,0,0,0,0,0,0,0,0,0,0,0,0,2,1,2,18000,66,0,0,1.000,0.0,0,0,Married,SSC,M,ConsumerLoan,others,P3
42062,0.000,0.00,1,0.500,0,0,0,0,0,2,0,15,8,58,0,0,0,0,0,0,0,0,0,0,0,0,0,242,0,12802,54,0,0,0.000,0.0,0,0,Single,UNDER GRADUATE,F,ConsumerLoan,others,P2
42063,0.000,0.00,0,0.000,0,0,0,0,1,0,0,20,20,74,0,0,0,10,0,0,0,0,0,0,0,0,0,13,1,16000,102,0,0,0.000,0.0,0,0,Married,SSC,M,others,others,P2

In [5]:
df.shape

(42064, 43)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 43 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Percent accounts opened in last 6 months                             42064 non-null  float64
 1   percent accounts closed in last 6 months                             42064 non-null  float64
 2   Total accounts closed in last 12 months                              42064 non-null  int64
 3   percent accounts closed in last 12 months                            42064 non-null  float64
 4   Total missed Payments                                                42064 non-null  int64
 5   Count of Credit card accounts                                        42064 non-null  int64
 6   Count of Housing loan accounts                                       42064 non-null  int64
 7   Count of Personal loan accounts                                      42064 non-null  int64
 8   Count of secured accounts                                            42064 non-null  int64
 9   Count of unsecured accounts                                          42064 non-null  int64
 10  Count of other accounts                                              42064 non-null  int64
 11  Age of oldest opened account                                         42064 non-null  int64
 12  Age of newest opened account                                         42064 non-null  int64
 13  Time Since recent Payment made                                       42064 non-null  int64
 14  Maximum recent level of delinquency                                  42064 non-null  int64
 15  Number of times delinquent between last 6 months and last 12 months  42064 non-null  int64
 16  Number of times 60+ dpd                                              42064 non-null  int64
 17  Number of standard Payments in last 12 months                        42064 non-null  int64
 18  Number of sub standard payments - not making full payments           42064 non-null  int64
 19  Number of sub standard payments in last 6 months                     42064 non-null  int64
 20  Number of sub standard payments in last 12 months                    42064 non-null  int64
 21  Number of doubtful payments                                          42064 non-null  int64
 22  Number of doubtful payments in last 12 months                        42064 non-null  int64
 23  Number of loss accounts                                              42064 non-null  int64
 24  Recent level of delinquency                                          42064 non-null  int64
 25  Credit card enquiries in last 12 months                              42064 non-null  int64
 26  Personal Loan enquiries in last 12 months                            42064 non-null  int64
 27  Time since recent enquiry                                            42064 non-null  int64
 28  Enquiries in last 3 months                                           42064 non-null  int64
 29  net monthly income                                                   42064 non-null  int64
 30  Time with current Employer                                           42064 non-null  int64
 31  Credit card Flag                                                     42064 non-null  int64
 32  Personal Loan Flag                                                   42064 non-null  int64
 33  Percent enquiries PL in last 6 months to last 6 months               42064 non-null  float64
 34  Percent enquiries CC in last 6 months to last 6 months               42064 non-null  float64
 35  Housing Loan Flag                                                    42064 non-null  int64
 36  Gold Loan Flag                                                       42064 non-null  int64
 37  Marital Status                                                       42064 non-null  object
 38  Education level                                                      42064 non-null  object
 39  gender                                                               42064 non-null  object
 40  Lates product enquired                                               42064 non-null  object
 41  First productd enquired                                              42064 non-null  object
 42  Approved_Flag                                                        42064 non-null  object
dtypes: float64(5), int64(32), object(6)
memory usage: 13.8+ MB

In [7]:
# Label encoding for the categorical features

In [8]:
df['Marital Status'].unique()

array(['Married', 'Single'], dtype=object)

In [9]:
df['Education level'].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE', 'UNDER GRADUATE',
       'OTHERS', 'PROFESSIONAL'], dtype=object)

In [10]:
df['gender'].unique()

array(['M', 'F'], dtype=object)

In [11]:
df['Lates product enquired'].unique()

array(['PL', 'ConsumerLoan', 'AL', 'CC', 'others', 'HL'], dtype=object)

In [12]:
df['First productd enquired'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 43 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Percent accounts opened in last 6 months                             42064 non-null  float64
 1   percent accounts closed in last 6 months                             42064 non-null  float64
 2   Total accounts closed in last 12 months                              42064 non-null  int64
 3   percent accounts closed in last 12 months                            42064 non-null  float64
 4   Total missed Payments                                                42064 non-null  int64
 5   Count of Credit card accounts                                        42064 non-null  int64
 6   Count of Housing loan accounts                                       42064 non-null  int64
 7   Count of Personal loan accounts                                      42064 non-null  int64
 8   Count of secured accounts                                            42064 non-null  int64
 9   Count of unsecured accounts                                          42064 non-null  int64
 10  Count of other accounts                                              42064 non-null  int64
 11  Age of oldest opened account                                         42064 non-null  int64
 12  Age of newest opened account                                         42064 non-null  int64
 13  Time Since recent Payment made                                       42064 non-null  int64
 14  Maximum recent level of delinquency                                  42064 non-null  int64
 15  Number of times delinquent between last 6 months and last 12 months  42064 non-null  int64
 16  Number of times 60+ dpd                                              42064 non-null  int64
 17  Number of standard Payments in last 12 months                        42064 non-null  int64
 18  Number of sub standard payments - not making full payments           42064 non-null  int64
 19  Number of sub standard payments in last 6 months                     42064 non-null  int64
 20  Number of sub standard payments in last 12 months                    42064 non-null  int64
 21  Number of doubtful payments                                          42064 non-null  int64
 22  Number of doubtful payments in last 12 months                        42064 non-null  int64
 23  Number of loss accounts                                              42064 non-null  int64
 24  Recent level of delinquency                                          42064 non-null  int64
 25  Credit card enquiries in last 12 months                              42064 non-null  int64
 26  Personal Loan enquiries in last 12 months                            42064 non-null  int64
 27  Time since recent enquiry                                            42064 non-null  int64
 28  Enquiries in last 3 months                                           42064 non-null  int64
 29  net monthly income                                                   42064 non-null  int64
 30  Time with current Employer                                           42064 non-null  int64
 31  Credit card Flag                                                     42064 non-null  int64
 32  Personal Loan Flag                                                   42064 non-null  int64
 33  Percent enquiries PL in last 6 months to last 6 months               42064 non-null  float64
 34  Percent enquiries CC in last 6 months to last 6 months               42064 non-null  float64
 35  Housing Loan Flag                                                    42064 non-null  int64
 36  Gold Loan Flag                                                       42064 non-null  int64
 37  Marital Status                                                       42064 non-null  object
 38  Education level                                                      42064 non-null  object
 39  gender                                                               42064 non-null  object
 40  Lates product enquired                                               42064 non-null  object
 41  First productd enquired                                              42064 non-null  object
 42  Approved_Flag                                                        42064 non-null  object
dtypes: float64(5), int64(32), object(6)
memory usage: 13.8+ MB

In [14]:
df.loc[df['Education level'] == 'SSC',['Education level']]              = 1
df.loc[df['Education level'] == '12TH',['Education level']]             = 2
df.loc[df['Education level'] == 'GRADUATE',['Education level']]         = 3
df.loc[df['Education level'] == 'UNDER GRADUATE',['Education level']]   = 3
df.loc[df['Education level'] == 'POST-GRADUATE',['Education level']]    = 4
df.loc[df['Education level'] == 'OTHERS',['Education level']]           = 1
df.loc[df['Education level'] == 'PROFESSIONAL',['Education level']]     = 3




df['Education level'].value_counts()
df['Education level'] = df['Education level'].astype(int)

In [15]:
df

,Percent accounts opened in last 6 months,percent accounts closed in last 6 months,Total accounts closed in last 12 months,percent accounts closed in last 12 months,Total missed Payments,Count of Credit card accounts,Count of Housing loan accounts,Count of Personal loan accounts,Count of secured accounts,Count of unsecured accounts,Count of other accounts,Age of oldest opened account,Age of newest opened account,Time Since recent Payment made,Maximum recent level of delinquency,Number of times delinquent between last 6 months and last 12 months,Number of times 60+ dpd,Number of standard Payments in last 12 months,Number of sub standard payments - not making full payments,Number of sub standard payments in last 6 months,Number of sub standard payments in last 12 months,Number of doubtful payments,Number of doubtful payments in last 12 months,Number of loss accounts,Recent level of delinquency,Credit card enquiries in last 12 months,Personal Loan enquiries in last 12 months,Time since recent enquiry,Enquiries in last 3 months,net monthly income,Time with current Employer,Credit card Flag,Personal Loan Flag,Percent enquiries PL in last 6 months to last 6 months,Percent enquiries CC in last 6 months to last 6 months,Housing Loan Flag,Gold Loan Flag,Marital Status,Education level,gender,Lates product enquired,First productd enquired,Approved_Flag
0,0.000,0.00,0,0.000,0,0,0,4,1,4,0,72,18,549,29,0,0,11,0,0,0,0,0,0,29,0,0,566,0,51000,114,0,1,0.000,0.0,1,0,Married,2,M,PL,PL,P2
1,0.000,0.00,0,0.000,0,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,209,0,19000,50,0,0,0.000,0.0,0,0,Single,3,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.00,0,0.000,1,0,0,0,2,6,0,47,2,302,25,8,0,10,0,0,0,0,0,0,25,0,0,587,0,18,191,0,0,0.000,0.0,1,0,Married,1,M,ConsumerLoan,others,P2
3,0.000,0.00,0,0.000,0,0,0,0,3,0,2,131,32,583,0,0,0,16,0,0,0,0,0,0,0,0,0,3951,0,15000,75,0,0,0.000,0.0,0,0,Married,4,M,AL,AL,P1
4,0.000,0.00,1,0.167,0,0,0,0,6,0,0,150,17,245,270,0,11,2,3,0,1,0,0,0,26,1,3,7,4,0,154,0,0,0.429,0.0,1,0,Married,2,M,ConsumerLoan,PL,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,0.333,0.00,0,0.000,0,0,0,0,0,3,1,24,5,15,24,0,0,0,0,0,0,0,0,0,24,0,0,0,1,18500,249,0,0,0.000,0.0,0,0,Married,2,M,ConsumerLoan,ConsumerLoan,P4
42060,0.000,0.25,1,0.250,0,0,0,0,2,2,0,74,7,57,0,0,0,6,0,0,0,0,0,0,0,0,0,203,0,25000,186,0,0,0.000,0.0,0,0,Married,1,M,others,others,P1
42061,0.500,0.50,1,0.500,0,0,0,0,0,2,0,9,5,32,0,0,0,0,0,0,0,0,0,0,0,0,2,1,2,18000,66,0,0,1.000,0.0,0,0,Married,1,M,ConsumerLoan,others,P3
42062,0.000,0.00,1,0.500,0,0,0,0,0,2,0,15,8,58,0,0,0,0,0,0,0,0,0,0,0,0,0,242,0,12802,54,0,0,0.000,0.0,0,0,Single,3,F,ConsumerLoan,others,P2
42063,0.000,0.00,0,0.000,0,0,0,0,1,0,0,20,20,74,0,0,0,10,0,0,0,0,0,0,0,0,0,13,1,16000,102,0,0,0.000,0.0,0,0,Married,1,M,others,others,P2

In [16]:
df_encoded = pd.get_dummies(df, columns=['Marital Status','gender', 'Lates product enquired' ,'First productd enquired'])

In [17]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 55 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Percent accounts opened in last 6 months                             42064 non-null  float64
 1   percent accounts closed in last 6 months                             42064 non-null  float64
 2   Total accounts closed in last 12 months                              42064 non-null  int64
 3   percent accounts closed in last 12 months                            42064 non-null  float64
 4   Total missed Payments                                                42064 non-null  int64
 5   Count of Credit card accounts                                        42064 non-null  int64
 6   Count of Housing loan accounts                                       42064 non-null  int64
 7   Count of Personal loan accounts                                      42064 non-null  int64
 8   Count of secured accounts                                            42064 non-null  int64
 9   Count of unsecured accounts                                          42064 non-null  int64
 10  Count of other accounts                                              42064 non-null  int64
 11  Age of oldest opened account                                         42064 non-null  int64
 12  Age of newest opened account                                         42064 non-null  int64
 13  Time Since recent Payment made                                       42064 non-null  int64
 14  Maximum recent level of delinquency                                  42064 non-null  int64
 15  Number of times delinquent between last 6 months and last 12 months  42064 non-null  int64
 16  Number of times 60+ dpd                                              42064 non-null  int64
 17  Number of standard Payments in last 12 months                        42064 non-null  int64
 18  Number of sub standard payments - not making full payments           42064 non-null  int64
 19  Number of sub standard payments in last 6 months                     42064 non-null  int64
 20  Number of sub standard payments in last 12 months                    42064 non-null  int64
 21  Number of doubtful payments                                          42064 non-null  int64
 22  Number of doubtful payments in last 12 months                        42064 non-null  int64
 23  Number of loss accounts                                              42064 non-null  int64
 24  Recent level of delinquency                                          42064 non-null  int64
 25  Credit card enquiries in last 12 months                              42064 non-null  int64
 26  Personal Loan enquiries in last 12 months                            42064 non-null  int64
 27  Time since recent enquiry                                            42064 non-null  int64
 28  Enquiries in last 3 months                                           42064 non-null  int64
 29  net monthly income                                                   42064 non-null  int64
 30  Time with current Employer                                           42064 non-null  int64
 31  Credit card Flag                                                     42064 non-null  int64
 32  Personal Loan Flag                                                   42064 non-null  int64
 33  Percent enquiries PL in last 6 months to last 6 months               42064 non-null  float64
 34  Percent enquiries CC in last 6 months to last 6 months               42064 non-null  float64
 35  Housing Loan Flag                                                    42064 non-null  int64
 36  Gold Loan Flag                                                       42064 non-null  int64
 37  Education level                                                      42064 non-null  int32
 38  Approved_Flag                                                        42064 non-null  object
 39  Marital Status_Married                                               42064 non-null  bool
 40  Marital Status_Single                                                42064 non-null  bool
 41  gender_F                                                             42064 non-null  bool
 42  gender_M                                                             42064 non-null  bool
 43  Lates product enquired_AL                                            42064 non-null  bool
 44  Lates product enquired_CC                                            42064 non-null  bool
 45  Lates product enquired_ConsumerLoan                                  42064 non-null  bool
 46  Lates product enquired_HL                                            42064 non-null  bool
 47  Lates product enquired_PL                                            42064 non-null  bool
 48  Lates product enquired_others                                        42064 non-null  bool
 49  First productd enquired_AL                                           42064 non-null  bool
 50  First productd enquired_CC                                           42064 non-null  bool
 51  First productd enquired_ConsumerLoan                                 42064 non-null  bool
 52  First productd enquired_HL                                           42064 non-null  bool
 53  First productd enquired_PL                                           42064 non-null  bool
 54  First productd enquired_others                                       42064 non-null  bool
dtypes: bool(16), float64(5), int32(1), int64(32), object(1)
memory usage: 13.0+ MB

In [18]:
k = df_encoded.describe()

In [19]:
k

,Percent accounts opened in last 6 months,percent accounts closed in last 6 months,Total accounts closed in last 12 months,percent accounts closed in last 12 months,Total missed Payments,Count of Credit card accounts,Count of Housing loan accounts,Count of Personal loan accounts,Count of secured accounts,Count of unsecured accounts,Count of other accounts,Age of oldest opened account,Age of newest opened account,Time Since recent Payment made,Maximum recent level of delinquency,Number of times delinquent between last 6 months and last 12 months,Number of times 60+ dpd,Number of standard Payments in last 12 months,Number of sub standard payments - not making full payments,Number of sub standard payments in last 6 months,Number of sub standard payments in last 12 months,Number of doubtful payments,Number of doubtful payments in last 12 months,Number of loss accounts,Recent level of delinquency,Credit card enquiries in last 12 months,Personal Loan enquiries in last 12 months,Time since recent enquiry,Enquiries in last 3 months,net monthly income,Time with current Employer,Credit card Flag,Personal Loan Flag,Percent enquiries PL in last 6 months to last 6 months,Percent enquiries CC in last 6 months to last 6 months,Housing Loan Flag,Gold Loan Flag,Education level
count,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.00000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,4.206400e+04,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000
mean,0.179032,0.097783,0.825504,0.160365,0.525746,0.145921,0.076241,0.328000,2.921334,2.341646,1.116489,46.498074,13.970046,218.601607,14.314758,0.336963,0.438879,3.279978,0.063831,0.002211,0.009224,0.02451,0.004279,0.016713,11.803918,0.268924,0.779194,264.854507,1.230458,2.692990e+04,110.345783,0.102962,0.193063,0.195497,0.064186,0.252235,0.056580,2.313689
std,0.278043,0.210957,1.537208,0.258831,1.106442,0.549314,0.358582,0.916368,6.379764,3.405397,2.486801,42.109230,18.835191,422.282417,54.056303,1.097356,2.148400,7.566312,0.799989,0.081704,0.220786,0.62189,0.184461,0.573762,46.422091,1.019459,1.802092,466.585002,2.069461,2.084300e+04,75.629967,0.303913,0.394707,0.367414,0.225989,0.434300,0.231042,0.871070
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,4.000000,51.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,1.800000e+04,61.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,34.000000,7.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,79.000000,1.000000,2.400000e+04,92.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,0.333000,0.100000,1.000000,0.250000,1.000000,0.000000,0.000000,0.000000,3.000000,3.000000,1.000000,65.000000,16.000000,146.000000,15.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,11.000000,0.000000,1.000000,302.000000,2.000000,3.100000e+04,131.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,3.000000
max,1.000000,1.000000,33.000000,1.000000,34.000000,27.000000,10.000000,29.000000,235.000000,55.000000,80.000000,385.000000,359.000000,6065.000000,900.000000,20.000000,52.000000,122.000000,41.000000,5.000000,12.000000,35.00000,12.000000,72.000000,900.000000,24.000000,44.000000,4768.000000,42.000000,2.500000e+06,1020.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000

In [20]:
y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
# 1. LogisticRegression
from sklearn.linear_model import LogisticRegression


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


LG_model = LogisticRegression(multi_class='auto', solver='lbfgs', max_iter=1000)
LG_model.fit(x_train, y_train)
y_pred = LG_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.63

Class p1:
Precision: 0.6226415094339622
Recall: 0.4230769230769231
F1 Score: 0.5038167938931297

Class p2:
Precision: 0.6322691747251291
Recall: 0.9460852329038653
F1 Score: 0.7579799904716532

Class p3:
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

Class p4:
Precision: 0.5432098765432098
Recall: 0.08551992225461613
F1 Score: 0.14777497900923592

C:\Users\HARSHIT JAIN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [23]:
# 2. KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


knn_model = KNeighborsClassifier()
knn_model.fit(x_train, y_train)
y_pred = knn_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.61

Class p1:
Precision: 0.5848142164781907
Recall: 0.35700197238658776
F1 Score: 0.4433557868952847

Class p2:
Precision: 0.666003367518751
Recall: 0.8624380574826561
F1 Score: 0.7515978580065642

Class p3:
Precision: 0.29322268326417705
Recall: 0.16
F1 Score: 0.20703125000000003

Class p4:
Precision: 0.395910780669145
Recall: 0.20699708454810495
F1 Score: 0.27185705169112956

In [24]:
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=10)
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.71

Class p1:
Precision: 0.7189030362389814
Recall: 0.7238658777120316
F1 Score: 0.7213759213759213

Class p2:
Precision: 0.8088006230529595
Recall: 0.8233894945490585
F1 Score: 0.8160298595422848

Class p3:
Precision: 0.3413078149920255
Recall: 0.3230188679245283
F1 Score: 0.33191159364094613

Class p4:
Precision: 0.6457085828343313
Recall: 0.6287657920310982
F1 Score: 0.637124569177745

In [25]:
# 4. Random Forest

rf_classifier = RandomForestClassifier()

rf_classifier.fit(x_train, y_train)
y_pred = rf_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy}')
print ()
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)


for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.7638179008677047

Class p1:
Precision: 0.8321678321678322
Recall: 0.7041420118343196
F1 Score: 0.7628205128205128

Class p2:
Precision: 0.7967687074829932
Recall: 0.9286422200198216
F1 Score: 0.8576659038901603

Class p3:
Precision: 0.44036697247706424
Recall: 0.21735849056603773
F1 Score: 0.29105608893380497

Class p4:
Precision: 0.7238001958863859
Recall: 0.718172983479106
F1 Score: 0.7209756097560976

In [26]:
# 5. xgboost

import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4)



y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.78

Class p1:
Precision: 0.823906083244397
Recall: 0.7613412228796844
F1 Score: 0.7913890312660173

Class p2:
Precision: 0.8255418233924413
Recall: 0.913577799801784
F1 Score: 0.8673315769665036

Class p3:
Precision: 0.4756380510440835
Recall: 0.30943396226415093
F1 Score: 0.3749428440786465

Class p4:
Precision: 0.7342386032977691
Recall: 0.7356656948493683
F1 Score: 0.7349514563106796

In [27]:
# 6. GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier

y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


GB_model = GradientBoostingClassifier()
GB_model.fit(x_train, y_train)
y_pred = GB_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.78

Class p1:
Precision: 0.8470066518847007
Recall: 0.7534516765285996
F1 Score: 0.7974947807933195

Class p2:
Precision: 0.8098918083462133
Recall: 0.934786917740337
F1 Score: 0.867868973132131

Class p3:
Precision: 0.4831932773109244
Recall: 0.26037735849056604
F1 Score: 0.3384011770475724

Class p4:
Precision: 0.7453798767967146
Recall: 0.7055393586005831
F1 Score: 0.72491263105342

# Hyperparameter Tuning

In [28]:
param_grid = {
    'n_estimators': [10, 50, 100],
      'learning_rate': [0.001 , 0.01 , 0.1, 1],
        'max_depth': [3, 5, 8, 10],
           'colsample_bytree': [0.1,0.3,0.5,0.7, 0.9],
              'alpha': [1, 10, 100]
}

index = 0

answer_grid = {
    'combination' : [],
    'train_accuracy' : [],
    'test_accuracy' : [],
    'n_estimators': [],
    'learning_rate': [],
    'max_depth': [],
    'colsample_bytree': [],
    'alpha': []
}


for colsample_bytree in param_grid['colsample_bytree']:
    for n_estimators in param_grid['n_estimators']:
        for learning_rate in param_grid['learning_rate']:
            for max_depth in param_grid['max_depth']:
                for alpha in param_grid['alpha']:
        
                   index = index + 1
         
        
        
                   model = xgb.XGBClassifier(objective='multi:softmax',  num_class=4,colsample_bytree = colsample_bytree,
                                                   learning_rate = learning_rate,
                                                  max_depth = max_depth,
                                                  alpha = alpha,
                                           n_estimators = n_estimators)



            y = df_encoded['Approved_Flag']
            x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


            label_encoder = LabelEncoder()
            y_encoded = label_encoder.fit_transform(y)


            x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




            model.fit(x_train, y_train)
            
            y_pred_train = model.predict(x_train)
            y_pred_test = model.predict(x_test)
            
            train_accuracy = accuracy_score(y_train,y_pred_train)
            test_accuracy = accuracy_score(y_test,y_pred_test)
            
            answer_grid['combination'] .append(index)
            answer_grid['train_accuracy'] .append(train_accuracy)
            answer_grid['test_accuracy'] .append(test_accuracy)
            answer_grid['colsample_bytree'] .append(colsample_bytree)
            answer_grid['learning_rate'] .append(learning_rate)
            answer_grid['alpha'] .append(alpha)
            answer_grid['max_depth'] .append(max_depth)
            answer_grid['n_estimators'] .append(n_estimators)
            
            
            print(f"combination{index}")
            print(f"colsample_bytree :{colsample_bytree}, learning_rate :{learning_rate}, alpha : {alpha}, max_depth :{max_depth}, n_estimators : {n_estimators}")
            print(f"train_accuracy : {train_accuracy : .2f}")
            print(f"test_accuracy : {test_accuracy : .2f}")
            print("-" * 30)

combination12
colsample_bytree :0.1, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination24
colsample_bytree :0.1, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination36
colsample_bytree :0.1, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination48
colsample_bytree :0.1, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.67
test_accuracy :  0.67
------------------------------
combination60
colsample_bytree :0.1, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination72
colsample_bytree :0.1, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination84
colsample_bytree :0.1, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.65
test_accuracy :  0.65
------------------------------
combination96
colsample_bytree :0.1, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.75
test_accuracy :  0.75
------------------------------
combination108
colsample_bytree :0.1, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination120
colsample_bytree :0.1, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.61
test_accuracy :  0.60
------------------------------
combination132
colsample_bytree :0.1, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.70
test_accuracy :  0.69
------------------------------
combination144
colsample_bytree :0.1, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.76
test_accuracy :  0.75
------------------------------
combination156
colsample_bytree :0.3, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.66
test_accuracy :  0.65
------------------------------
combination168
colsample_bytree :0.3, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.66
test_accuracy :  0.66
------------------------------
combination180
colsample_bytree :0.3, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.68
test_accuracy :  0.67
------------------------------
combination192
colsample_bytree :0.3, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.75
test_accuracy :  0.74
------------------------------
combination204
colsample_bytree :0.3, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.66
test_accuracy :  0.65
------------------------------
combination216
colsample_bytree :0.3, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.67
test_accuracy :  0.66
------------------------------
combination228
colsample_bytree :0.3, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.74
test_accuracy :  0.72
------------------------------
combination240
colsample_bytree :0.3, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination252
colsample_bytree :0.3, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.66
test_accuracy :  0.65
------------------------------
combination264
colsample_bytree :0.3, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.68
test_accuracy :  0.67
------------------------------
combination276
colsample_bytree :0.3, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.76
test_accuracy :  0.75
------------------------------
combination288
colsample_bytree :0.3, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination300
colsample_bytree :0.5, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.69
test_accuracy :  0.69
------------------------------
combination312
colsample_bytree :0.5, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.69
test_accuracy :  0.69
------------------------------
combination324
colsample_bytree :0.5, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.71
test_accuracy :  0.70
------------------------------
combination336
colsample_bytree :0.5, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.77
test_accuracy :  0.76
------------------------------
combination348
colsample_bytree :0.5, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.70
test_accuracy :  0.70
------------------------------
combination360
colsample_bytree :0.5, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.71
test_accuracy :  0.71
------------------------------
combination372
colsample_bytree :0.5, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.76
test_accuracy :  0.75
------------------------------
combination384
colsample_bytree :0.5, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination396
colsample_bytree :0.5, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.71
test_accuracy :  0.70
------------------------------
combination408
colsample_bytree :0.5, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.73
test_accuracy :  0.71
------------------------------
combination420
colsample_bytree :0.5, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination432
colsample_bytree :0.5, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination444
colsample_bytree :0.7, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.74
test_accuracy :  0.73
------------------------------
combination456
colsample_bytree :0.7, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.74
test_accuracy :  0.73
------------------------------
combination468
colsample_bytree :0.7, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.74
test_accuracy :  0.74
------------------------------
combination480
colsample_bytree :0.7, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination492
colsample_bytree :0.7, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.74
test_accuracy :  0.73
------------------------------
combination504
colsample_bytree :0.7, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.74
test_accuracy :  0.74
------------------------------
combination516
colsample_bytree :0.7, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.77
test_accuracy :  0.76
------------------------------
combination528
colsample_bytree :0.7, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.79
test_accuracy :  0.77
------------------------------
combination540
colsample_bytree :0.7, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.74
test_accuracy :  0.73
------------------------------
combination552
colsample_bytree :0.7, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.75
test_accuracy :  0.74
------------------------------

combination564
colsample_bytree :0.7, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination576
colsample_bytree :0.7, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.79
test_accuracy :  0.77
------------------------------
combination588
colsample_bytree :0.9, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.75
test_accuracy :  0.74
------------------------------
combination600
colsample_bytree :0.9, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.75
test_accuracy :  0.74
------------------------------
combination612
colsample_bytree :0.9, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.75
test_accuracy :  0.74
------------------------------
combination624
colsample_bytree :0.9, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 10
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination636
colsample_bytree :0.9, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.76
test_accuracy :  0.75
------------------------------
combination648
colsample_bytree :0.9, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.75
test_accuracy :  0.74
------------------------------
combination660
colsample_bytree :0.9, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination672
colsample_bytree :0.9, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 50
train_accuracy :  0.79
test_accuracy :  0.77
------------------------------
combination684
colsample_bytree :0.9, learning_rate :0.001, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.75
test_accuracy :  0.75
------------------------------
combination696
colsample_bytree :0.9, learning_rate :0.01, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.76
test_accuracy :  0.75
------------------------------
combination708
colsample_bytree :0.9, learning_rate :0.1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.78
test_accuracy :  0.77
------------------------------
combination720
colsample_bytree :0.9, learning_rate :1, alpha : 100, max_depth :10, n_estimators : 100
train_accuracy :  0.79
test_accuracy :  0.77
------------------------------

In [29]:
xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4 , colsample_bytree = 0.9, learning_rate = 1, 
                                   alpha = 10, max_depth = 3, n_estimators = 100)


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.78

Class p1:
Precision: 0.8331539289558665
Recall: 0.7633136094674556
F1 Score: 0.7967061245496656

Class p2:
Precision: 0.8218033078427885
Recall: 0.9159563924677899
F1 Score: 0.866329208848894

Class p3:
Precision: 0.4658018867924528
Recall: 0.2981132075471698
F1 Score: 0.36355269213069485

Class p4:
Precision: 0.7374136229022705
Recall: 0.7259475218658892
F1 Score: 0.7316356513222332